[project]
name = "gemma-finetune"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi",
    "uvicorn",
    "jinja2",
    "pydantic",
    "transformers",
    "torch",
]
